[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Andrew Rhyne <rhyneandrew@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
image = "0.21.3"
crossbeam = "0.2.8"
num_cpus = "1.0"